apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: sap-cpi-toolkit
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
  namespace: sap-cpi-toolkit
spec:
  storageClassName: local-path
