apiVersion: v1
kind: Secret
metadata:
  name: postgres
stringData:
  POSTGRES_USER: toolkit
  POSTGRES_PASSWORD: toolkit
  POSTGRES_DB: toolkit
  DB_URL: postgres://toolkit:toolkit@postgres:5432/toolkit?sslmode=disable
