apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  PORT: "3000"
  BASE_URL: http://localhost
  DEPLOYMENT_ENV: local
  AUTH_BYPASS_ENABLED: "true"
  WORKER_INTERNAL_URL: http://worker:8081
  GROOVY_INTERNAL_URL: http://groovy-runner:8082
